version: '3.4'

services:
  eshop.modernized.mvc:
    image: eshop/modernizedmvc
    build:
      args: 
        source: D:\a\1\s\eShopModernizedMVCSolution\src\eShopModernizedMVC\obj\Release\Package\PackageTmp\
      context: .\src\eShopModernizedMVC
      dockerfile: Dockerfile
    depends_on:
      - sql.data

  sql.data:
    image: microsoft/mssql-server-windows-developer
